const defaultPageContents = {
  home: {
    heroBadge: 'UKM DKV — Universitas Merangin',
    heroTitle1: 'Ideas Become',
    heroTitle1Highlight: 'Reality,',
    heroTitle2: 'Visuals Become',
    heroTitle2Highlight: 'Stories',
    heroCtaText: 'Eksplorasi Portofolio',
    heroCtaLink: '/portfolio',
    divisionRibbonTitle: '4 Divisi Utama:',
    divisionRibbonItems: ['Desain', 'Photography', 'Videography', 'Public Relation (PR)'],
    camavisBannerTag: 'REKRUTMEN TERBUKA',
    camavisBannerTitle: 'Bergabung sebagai CAMAVIS?',
    camavisBannerDesc: 'Wujudkan ide kreatifmu dan jadilah bagian dari keluarga besar Desain Komunikasi Visual Universitas Merangin.',
    camavisBannerCtaText: 'Daftar Sekarang',
    camavisBannerCtaLink: '/camavis',
  },
  about: {
    badge: 'DKV PHILOSOPHY & IDENTITY',
    title: 'Tentang DKV Universitas Merangin',
    subtitle: 'Wadah eksplorasi visual, inovasi desain, dan karya kreatif mahasiswa Universitas Merangin.',
    introTitle: 'Mengenal DKV Universitas Merangin',
    introDesc1: 'DEKAVE (DKV Universitas Merangin) adalah Unit Kegiatan Mahasiswa yang berfokus pada pengembangan bakat, kreativitas, dan wawasan profesional dalam Desain Komunikasi Visual. Kami mewadahi mahasiswa dari berbagai latar belakang yang memiliki minat mendalam pada desain grafis, ilustrasi, fotografi, videografi, serta media komunikasi kreatif.',
    introDesc2: 'Di UKM DKV, kami bergerak bersama dalam 4 divisi spesialisasi: Desain, Photography, Videography, dan Public Relation (PR). Setiap divisi saling berkolaborasi dari tahap ide, produksi visual, hingga publikasi ke audiens kampus dan masyarakat luas.',
    quoteText: 'Ideas Become Reality, Visuals Become Stories',
    quoteAuthor: 'Motto Resmi DKV Universitas Merangin',
    visionTitle: 'Visi Kami',
    visionText: 'Menjadi wadah kreativitas visual terdepan di lingkungan kampus yang adaptif terhadap perkembangan teknologi dan industri kreatif, serta menghasilkan karya-karya visual berdaya saing tinggi.',
    missionTitle: 'Misi Kami',
    missionItems: [
      'Membangun unit kegiatan yang aktif dan kolaboratif untuk saling berbagi ilmu serta pengalaman di bidang DKV.',
      'Meningkatkan kualitas serta daya saing anggota melalui kompetisi, pameran, dan proyek kreatif.',
      'Menjalin kerja sama dengan pihak eksternal, termasuk industri kreatif, untuk membuka peluang magang dan proyek bersama.',
      'Mendorong inovasi dan eksplorasi desain yang tidak hanya estetis, tetapi juga memiliki nilai komunikasi yang kuat.',
      'Menjadi wadah bagi mahasiswa untuk menyalurkan minat dan bakat di bidang desain grafis, animasi, fotografi, videografi dan media interaktif.'
    ],
  },
  contact: {
    badge: 'HUBUNGI KAMI & FAST CONNECT',
    title: 'Hubungi Kami',
    subtitle: 'Ada pertanyaan, ingin berkolaborasi, atau butuh konsultasi desain? Hubungi tim pengurus DKV Universitas Merangin sekarang.',
    formTitle: 'Kirim Pesan ke DKV',
    formSubtitle: 'Isi pesan dan kami akan otomatis mengarahkan ke WhatsApp resmi DKV dengan format yang rapi.',
    campusAddress: 'Kampus Universitas Merangin, Bangko, Jambi',
    email: 'viscode0um@gmail.com',
    whatsappNumber: '6282289656828',
    whatsappDisplay: '+62 822-8965-6828',
    instagramHandle: '@viscode_um',
    instagramUrl: 'https://www.instagram.com/viscode_um/',
    tiktokHandle: '@viscode_univmerangin',
    tiktokUrl: 'https://www.tiktok.com/@viscode_univmerangin?_r=1&_t=ZS-9ACLSGdOjH4',
  },
};

module.exports = defaultPageContents;
